### ISSUE TITLE
recursion_limit

### ISSUE THREAD

**Issue by Hunstagamez** [mikekelly/AgentK#13]
So basically whenever the system tries to do something, it's eventually caught off by `An error occurred while assigning software_engineer to task clean-up or potentially recover the identified incomplete or corrupted files in the tools and agents directories:
 Recursion limit of 25 reached without hitting a stop condition. You can increase the limit by setting the `recursion_limit` config key.
Traceback (most recent call last):
  File "/app/tools/assign_agent_to_task.py", line 14, in assign_agent_to_task
    result = agent_function(task=task)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/agents/software_engineer.py", line 71, in software_engineer
    return graph.invoke(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 1299, in invoke
    for chunk in self.stream(
                 ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 1004, in stream
    raise GraphRecursionError(
langgraph.errors.GraphRecursionError: Recursion limit of 25 reached without hitting a stop condition. You can increase the limit by setting the `recursion_limit` config key.`

Where can I find this recursion_limit config key? I search far and wide through the code and really could not find it. Is it within lang api? If it is, I thought lang was optional. Help would be greatly appreciated as this is otherwise an incredible system. Thanks.

**Comment by Hunstagamez** [comment]
Turns out it was a per-agent option. Down the bottom, in each agent.py they have their configs in graph_invoke, and you can add a recursion_limit and mess with it. Setting each to 100 did the trick for me. See below:

`    return graph.invoke(
        {"messages": [SystemMessage(system_prompt)]},
        config={
            "configurable": {"thread_id": uuid},
            "recursion_limit": 100
        }
    )`
