### ISSUE TITLE
Error Unable to run agentk

### ISSUE THREAD

**Issue by JustinYLee** [mikekelly/AgentK#15]
I get following error when I try to run ./agentk after successful install.  I tried it from WSL2 and miniconda3 on Linux Mint install.

Traceback (most recent call last):
  File "/app/agent_kernel.py", line 4, in <module>
    from agents import hermes
  File "/app/agents/hermes.py", line 7, in <module>
    import utils
  File "/app/utils.py", line 8, in <module>
    from langgraph.checkpoint.sqlite import SqliteSaver
  File "/usr/local/lib/python3.12/site-packages/langgraph/checkpoint/sqlite/__init__.py", line 9, in <module>
    from langgraph.checkpoint.base import (
ImportError: cannot import name 'WRITES_IDX_MAP' from 'langgraph.checkpoint.base' (/usr/local/lib/python3.12/site-packages/langgraph/checkpoint/base/__init__.py)

**Comment by ramontayag** [comment]
Same as https://github.com/mikekelly/AgentK/issues/18#issuecomment-2396543413
