### ISSUE TITLE
❌ unhandled err breaks install - cannot import name 'WRITES_IDX_MAP' from 'langgraph.checkpoint.base

### ISSUE THREAD

**Issue by 6rz6** [mikekelly/AgentK#18]
err during install: 
installing on ubuntu jammy with py 3.10.12:

=> => exporting layers                                                                                                                                                                                      21.0s 
 => => writing image sha256:b2e056e5531aaeff2114f2ec0a9e585124c4a603250d159252b190dcfb9b3e48                                                                                                                  0.0s 
 => => naming to docker.io/library/agentk-agentk                                                                                                                                                              0.0s 
 => [agentk] resolving provenance for metadata file                                                                                                                                                           0.0s
Traceback (most recent call last):
  File "/app/agent_kernel.py", line 4, in <module>
    from agents import hermes
  File "/app/agents/hermes.py", line 7, in <module>
    import utils
  File "/app/utils.py", line 8, in <module>
    from langgraph.checkpoint.sqlite import SqliteSaver
  File "/usr/local/lib/python3.12/site-packages/langgraph/checkpoint/sqlite/__init__.py", line 9, in <module>
    from langgraph.checkpoint.base import (
**ImportError: cannot import name 'WRITES_IDX_MAP' from 'langgraph.checkpoint.base' (/usr/local/lib/python3.12/site-packages/**langgraph/checkpoint/base/__init__.py)
(agentk) root@s0-2v4-ams3:~/dev/AgentK#

**Comment by ramontayag** [comment]
Check out https://github.com/langchain-ai/langgraph/issues/1570

**Comment by ahmetax** [comment]
ImportError: cannot import name 'WRITES_IDX_MAP' from 'langgraph.checkpoint.base' on Ubuntu 24.04. Although I tried almost all versions of libraries, no success! 
I also tried to change the python version to 3.10,  by changin the first line in Dockerfile as "FROM python:3.10-bullseye", it still installs Python3.13.
This is a good project. It would be nice to be able to run it!...

**Comment by clickbrain** [comment]
Same
